import { Router } from "express";
import { promises as fs } from "node:fs";
import path from "node:path";
import { spawn, type ChildProcess } from "node:child_process";
import { desc, eq } from "drizzle-orm";
import { buildApps, db } from "@workspace/db";
import {
  ensureWorkspace,
  getSessionCwd,
  getWorkspaceCommandEnvironment,
  getWorkspaceRoot,
  listWorkspaceFiles,
  readWorkspaceFile,
  writeWorkspaceFile,
  runTerminalCommand,
  renameWorkspacePath,
  deleteWorkspacePath,
  WORKSPACE_ROOT,
} from "../../lib/workspace";
import { getStorage, persistFile } from "../../lib/storage";
import { jarvisConfig } from "../../config/jarvis";
import { pooledClient } from "../../lib/llm-client";
import { searchFiles, replaceInFiles } from "./search";
import type { Browser, Page } from "puppeteer";

const puppeteerPromise = import("puppeteer");

const router = Router();
const previewProcesses = new Map<string, { child: ChildProcess; port: number; command: string; output: string }>();

function previewKey(workspaceId: string, sessionId: string): string {
  return `${workspaceId}:${sessionId}`;
}

/**
 * LLM-backed starter project generation. The model is asked to return a JSON
 * object mapping relative file paths to file contents. The response is parsed
 * leniently, and a deterministic single-page fallback is used when the model
 * is unavailable or returns something unparseable, so the studio always gets
 * a working starter.
 */
async function generateStarterFiles(
  prompt: string,
  answers: Record<string, string>,
  feedback: string | null,
  existingFiles: string[],
  extraSystemPrompt = "",
  plan: BuildPlan | null = null,
): Promise<Record<string, string>> {
  const userSummary = Object.entries(answers)
    .map(([question, answer]) => `${question}: ${answer}`)
    .join("\n");
  const existing = existingFiles.length > 0
    ? `\nExisting files in the workspace (keep and update them, do not duplicate):\n${existingFiles.join("\n")}`
    : "";
  const feedbackLine = feedback ? `\nThe user reviewed a preview and asked for these changes:\n${feedback}\n\nApply the changes and return the COMPLETE updated content of every file that changes (and any new files).` : "";

  // Themed fallback so a failed LLM pass never ships the old "generated
  // locally by Jarvis" stub: it at least reflects the request's subject and
  // looks intentional.
  const fallback = (): Record<string, string> => {
    const title = (prompt.split(/[\n.,]/)[0] || "My App").trim().slice(0, 60) || "My App";
    const escaped = title.replace(/[<>&"]/g, (ch) => ({ "<": "&lt;", ">": "&gt;", "&": "&amp;", '"': "&quot;" })[ch] ?? ch);
    const warm = /\b(bakery|cafe|cafe|coffee|restaurant|food|bistro|kitchen|pizza)\b/i.test(prompt);
    const c1 = warm ? "#7a3c1d" : "#1b2a4a";
    const c2 = warm ? "#f7e8d4" : "#e8eefc";
    const html = `<!doctype html>\n<html lang="en">\n<head>\n<meta charset="UTF-8">\n<meta name="viewport" content="width=device-width, initial-scale=1">\n<title>${escaped}</title>\n<style>\n:root{color-scheme:dark}\n*{box-sizing:border-box}\nbody{margin:0;font-family:system-ui,-apple-system,sans-serif;background:radial-gradient(1200px 600px at 20% -10%,${c1},#0b1020 55%);color:${c2};min-height:100vh;display:grid;place-items:center;padding:24px}\nmain{max-width:680px;width:100%;padding:48px;border:1px solid rgba(255,255,255,.12);border-radius:24px;background:rgba(21,29,51,.55);backdrop-filter:blur(8px)}\nh1{margin:0 0 8px;font-size:2rem}\np{line-height:1.7;opacity:.85;margin:8px 0 24px}\na{display:inline-block;background:#8fb3ff;color:#0b1020;border-radius:12px;padding:12px 20px;font-weight:600;text-decoration:none}\na:hover{filter:brightness(1.1)}\n</style>\n</head>\n<body>\n<main>\n<h1>${escaped}</h1>\n<p>Your ${escaped.toLowerCase().includes("bakery") ? "bakery" : "project"} page is ready. This starter reflects your idea; type a follow-up in the chat to refine it, or iterate from the Build tab.</p>\n<a href="#">Get started</a>\n</main>\n</body>\n</html>\n`;
    return { "index.html": html, "README.md": `# ${escaped}\n\nStarter generated by Jarvis.\n` };
  };

  const systemPrompt = withExtraBuildInstructions(
    "You are the scaffolding engine inside a web-based IDE. The user wants a starter project built. " +
    "Return ONLY a valid JSON object where each key is a relative file path and each value is the complete file content. " +
    "No markdown fences, no explanation, no extra text before or after the JSON. " +
    "Build a complete, polished single-page app with vanilla HTML, CSS and JavaScript (no external build step, it must run from a static server). " +
    "Prefer a single self-contained index.html with all CSS and JavaScript inline; only split into extra files when genuinely useful. " +
    "The page must actually realize the user's request: real heading, real content, working sections, tasteful modern styling, responsive. " +
    "Keep the starter focused and small (well under 3000 tokens total) so it completes in one response. " +
    "Escape backslashes and quotes correctly inside the JSON string values. " +
    "Never use the em dash character anywhere in generated content.",
    extraSystemPrompt,
  );
  const userContent = `The user wants: ${prompt}\n\nAnswers to the clarifying questions:\n${userSummary || "(none provided)"}\n${feedbackLine}\n${existing}${plan ? `\nApproved implementation plan to follow:\n${JSON.stringify(plan)}` : ""}`;

  const run = (jsonMode: boolean) => pooledClient().chat.completions.create({
    model: jarvisConfig.llmModel,
    messages: [
      { role: "system", content: systemPrompt },
      { role: "user", content: userContent },
    ],
    temperature: 0.6,
    max_tokens: 8000,
    ...(jsonMode ? { response_format: { type: "json_object" as const } } : {}),
  }).then((completion) => parseStarterFiles(completion.choices[0]?.message?.content?.trim() ?? ""));

  // Strict JSON mode first (OpenRouter free models support it); if that is
  // rejected or parses to nothing, one plain retry, then the themed fallback.
  try {
    const files = await run(true);
    if (files) return files;
  } catch { /* json_object unsupported on this route — retry plain */ }
  try {
    const files = await run(false);
    if (files) return files;
  } catch { /* all LLM paths failed */ }
  return fallback();
}

/** Parse the scaffolding model's reply into a file map, tolerating markdown
 *  fences and stray text. Returns null when nothing usable came back. */
function parseStarterFiles(raw: string): Record<string, string> | null {
  if (!raw) return null;
  let parsed: unknown = null;
  try { parsed = JSON.parse(raw); } catch { /* try harder below */ }
  if (parsed === null) {
    try { parsed = JSON.parse(raw.replace(/```(?:json)?/gi, "").trim()); } catch { /* try block extract */ }
  }
  if (parsed === null) {
    const match = raw.match(/\{[\s\S]*\}/);
    if (match) { try { parsed = JSON.parse(match[0]); } catch { /* unrecoverable */ } }
  }
  if (!parsed || typeof parsed !== "object" || Array.isArray(parsed)) return null;
  const files: Record<string, string> = {};
  for (const [rel, content] of Object.entries(parsed as Record<string, unknown>)) {
    if (typeof rel !== "string" || !rel.trim() || rel.includes("\\")) continue;
    if (!/^[a-zA-Z0-9._/ -]+$/.test(rel) || rel.startsWith("/") || rel.includes("..")) continue;
    if (typeof content !== "string" || content.length > 200_000) continue;
    files[rel] = content;
  }
  return Object.keys(files).length > 0 ? files : null;
}

interface BuildPlan {
  title: string;
  summary: string;
  steps: string[];
  files: string[];
  risks: string[];
}

function fallbackBuildPlan(prompt: string, existingFiles: string[]): BuildPlan {
  const subject = cleanText(prompt, 120) || "the requested app";
  return {
    title: `Build plan: ${subject}`,
    summary: `Jarvis will turn this request into a runnable local build, preserve the existing workspace, and verify the result in the preview.`,
    steps: [
      `Translate the request into a focused implementation for ${subject}.`,
      "Inspect the current workspace and reuse existing files before creating new ones.",
      "Implement the smallest complete version with responsive, accessible UI and working interactions.",
      "Start the local preview, inspect the rendered result, and fix concrete runtime or completeness issues.",
    ],
    files: existingFiles.slice(0, 8),
    risks: ["The exact runtime and file boundaries will be confirmed from the existing workspace before edits."],
  };
}

function parseBuildPlan(raw: string, prompt: string, existingFiles: string[]): BuildPlan | null {
  const parsed = parseJsonObject(raw);
  if (!parsed) return null;
  const strings = (value: unknown, max: number) => Array.isArray(value)
    ? value.filter((item): item is string => typeof item === "string").map((item) => item.trim().slice(0, max)).filter(Boolean).slice(0, 12)
    : [];
  const fallback = fallbackBuildPlan(prompt, existingFiles);
  return {
    title: cleanText(parsed.title, 160) || fallback.title,
    summary: cleanText(parsed.summary, 1200) || fallback.summary,
    steps: strings(parsed.steps, 500).length > 0 ? strings(parsed.steps, 500) : fallback.steps,
    files: strings(parsed.files, 180).length > 0 ? strings(parsed.files, 180) : fallback.files,
    risks: strings(parsed.risks, 300),
  };
}

async function createBuildPlan(
  prompt: string,
  answers: Record<string, string>,
  existingFiles: string[],
  extraSystemPrompt = "",
): Promise<BuildPlan> {
  const fallback = fallbackBuildPlan(prompt, existingFiles);
  try {
    const completion = await pooledClient().chat.completions.create({
      model: jarvisConfig.llmModel,
      messages: [
        {
          role: "system",
          content: withExtraBuildInstructions(
            "You are the planning layer inside Jarvis Build. Plan substantial implementation requests before any files are changed. " +
            "Understand the user's requirements, inspect the listed workspace context, and produce a practical ordered plan for a local runnable app. " +
            "Do not write code and do not claim that anything has been implemented. Return ONLY valid JSON with this shape: " +
            "{title:string,summary:string,steps:string[],files:string[],risks:string[]}. " +
            "Keep the plan concrete, honest, and concise. Reuse existing files when appropriate. Never use the em dash character.",
            extraSystemPrompt,
          ),
        },
        {
          role: "user",
          content: `Request:\n${prompt}\n\nClarifying answers:\n${JSON.stringify(answers)}\n\nExisting workspace files:\n${existingFiles.join("\\n") || "(empty workspace)"}`,
        },
      ],
      temperature: 0.2,
      max_tokens: 900,
    });
    return parseBuildPlan(completion.choices[0]?.message?.content?.trim() ?? "", prompt, existingFiles) ?? fallback;
  } catch {
    return fallback;
  }
}

interface BuildReviewResult {
  done: boolean;
  summary: string;
  fixRequest: string | null;
  deferred: string[];
  filesChanged: string[];
}

function parseJsonObject(raw: string): Record<string, unknown> | null {
  const match = raw.match(/{[\s\S]*}/);
  if (!match) return null;
  try {
    const parsed = JSON.parse(match[0]) as unknown;
    return parsed && typeof parsed === "object" && !Array.isArray(parsed)
      ? parsed as Record<string, unknown>
      : null;
  } catch {
    return null;
  }
}

function reviewFallback(prompt: string, files: string[], previewOutput: string): BuildReviewResult {
  const hasIndex = files.some((file) => file.toLowerCase() === "index.html");
  const hasRuntimeError = /\b(error|failed|exception|not found|cannot|syntaxerror)\b/i.test(previewOutput);
  if (!hasIndex) {
    return {
      done: false,
      summary: "The preview is missing an index.html entry point.",
      fixRequest: `Create a complete index.html entry point for this app: ${prompt}`,
      deferred: [],
      filesChanged: [],
    };
  }
  return {
    done: !hasRuntimeError,
    summary: hasRuntimeError
      ? "The preview log contains a runtime error that needs another fix pass."
      : "The workspace has an HTML entry point and no reported runtime errors.",
    fixRequest: hasRuntimeError ? `Inspect and fix the runtime issue shown in this preview output:\n${previewOutput.slice(-3000)}` : null,
    deferred: ["Accessibility and visual review should still be confirmed from the rendered preview."],
    filesChanged: [],
  };
}

async function reviewAndFixWorkspace(
  prompt: string,
  answers: Record<string, string>,
  workspaceId: string,
  previewOutput: string,
  passNumber: number,
  extraSystemPrompt = "",
  plan: BuildPlan | null = null,
): Promise<BuildReviewResult> {
  const entries = await listWorkspaceFiles(workspaceId);
  const files = entries
    .filter((entry) => entry.type === "file" && !/^\\.?env/i.test(entry.path))
    .map((entry) => entry.path)
    .slice(0, 120);
  const fallback = reviewFallback(prompt, files, previewOutput);
  
  // Track token usage to warn users on high iteration count
  const tokenWarning = passNumber > 10 ? `(High iteration count: ${passNumber} passes. Consider if additional changes are needed.)` : "";
  
  try {
    const client = pooledClient();
    const completion = await client.chat.completions.create({
      model: jarvisConfig.llmModel,
      messages: [
        {
          role: "system",
          content:
            withExtraBuildInstructions(
              "You are the self-reviewer inside Jarvis Build. Review a locally generated web app after it has been run. " +
              "Return ONLY JSON with this shape: {done:boolean,summary:string,fixRequest:string|null,deferred:string[]}. " +
              "Set done false only when a concrete runtime, structure, or obvious completeness issue can be fixed now. " +
              "Keep fixRequest short and actionable. Do not claim that a screenshot, accessibility, security, or performance check passed unless evidence is provided. " +
              "Never use the em dash character.",
              extraSystemPrompt,
            ),
        },
        {
          role: "user",
          content:
            `Prompt: ${prompt}\nAnswers: ${JSON.stringify(answers)}\nPass: ${passNumber}${tokenWarning}\nFiles: ${files.join(", ") || "(none)"}\nPreview output:\n${previewOutput.slice(-6000)}`,
        },
      ],
      temperature: 0.1,
      max_tokens: 700,
    });
    const parsed = parseJsonObject(completion.choices[0]?.message?.content?.trim() ?? "");
    if (!parsed) return fallback;
    const done = parsed.done === true;
    const summary = cleanText(parsed.summary, 500) || fallback.summary;
    const fixRequest = done ? null : cleanText(parsed.fixRequest, 1800) || fallback.fixRequest;
    const deferred = Array.isArray(parsed.deferred)
      ? parsed.deferred.filter((item): item is string => typeof item === "string").map((item) => item.slice(0, 240)).slice(0, 8)
      : fallback.deferred;
    if (done || !fixRequest) return { done: true, summary, fixRequest: null, deferred, filesChanged: [] };

    const existingFiles = entries.filter((entry) => entry.type === "file").map((entry) => entry.path);
    const generated = await generateStarterFiles(prompt, answers, fixRequest, existingFiles, extraSystemPrompt, plan);
    const filesChanged: string[] = [];
    for (const [relativePath, content] of Object.entries(generated)) {
      if (!safeWorkspacePath(relativePath, workspaceId)) continue;
      await writeWorkspaceFile(relativePath, content, workspaceId);
      filesChanged.push(relativePath);
    }
    return { done: false, summary, fixRequest, deferred, filesChanged };
  } catch {
    if (fallback.done || !fallback.fixRequest) return fallback;
    const existingFiles = entries.filter((entry) => entry.type === "file").map((entry) => entry.path);
    const generated = await generateStarterFiles(prompt, answers, fallback.fixRequest, existingFiles, extraSystemPrompt, plan);
    const filesChanged: string[] = [];
    for (const [relativePath, content] of Object.entries(generated)) {
      if (!safeWorkspacePath(relativePath, workspaceId)) continue;
      await writeWorkspaceFile(relativePath, content, workspaceId);
      filesChanged.push(relativePath);
    }
    return { ...fallback, filesChanged };
  }
}

let screenshotBrowser: Browser | null = null;
let screenshotBrowserPromise: Promise<Browser> | null = null;

async function getScreenshotBrowser(): Promise<Browser> {
  if (screenshotBrowser && screenshotBrowser.connected) return screenshotBrowser;
  if (!screenshotBrowserPromise) {
    screenshotBrowserPromise = puppeteerPromise.then(async ({ default: puppeteer }) => {
      const executablePath = await puppeteer.executablePath();
      const browser = await puppeteer.launch({
        headless: true,
        executablePath,
        args: ["--no-sandbox", "--disable-setuid-sandbox", "--disable-gpu", "--mute-audio", "--disable-dev-shm-usage"],
      });
      screenshotBrowser = browser;
      return browser;
    }).catch((err) => {
      screenshotBrowserPromise = null;
      throw err;
    });
  }
  return screenshotBrowserPromise;
}

interface PreviewAgentElement {
  id: number;
  tag: string;
  text: string;
  ariaLabel: string;
  placeholder: string;
  inputType: string;
  href: string;
  disabled: boolean;
}

interface PreviewAgentAction {
  action: "click" | "type" | "select" | "press" | "wait" | "done";
  id?: number;
  text?: string;
  value?: string;
  key?: string;
  milliseconds?: number;
}

interface PreviewAgentDecision {
  done: boolean;
  message: string;
  actions: PreviewAgentAction[];
}

function localPreviewUrl(url: string, port: number): boolean {
  try {
    const parsed = new URL(url);
    return (parsed.hostname === "localhost" || parsed.hostname === "127.0.0.1") && parsed.port === String(port);
  } catch {
    return false;
  }
}

function parsePreviewAgentDecision(raw: string): PreviewAgentDecision | null {
  const parsed = parseJsonObject(raw);
  if (!parsed) return null;
  const actions = Array.isArray(parsed.actions) ? parsed.actions : [];
  const allowed = new Set<PreviewAgentAction["action"]>(["click", "type", "select", "press", "wait", "done"]);
  return {
    done: parsed.done === true,
    message: cleanText(parsed.message, 500),
    actions: actions
      .filter((item): item is Record<string, unknown> => Boolean(item) && typeof item === "object" && !Array.isArray(item))
      .map((item) => ({
        action: allowed.has(item.action as PreviewAgentAction["action"]) ? item.action as PreviewAgentAction["action"] : "done",
        id: Number.isInteger(item.id) ? Number(item.id) : undefined,
        text: cleanText(item.text, 1000),
        value: cleanText(item.value, 300),
        key: cleanText(item.key, 40),
        milliseconds: Math.min(2000, Math.max(0, Number(item.milliseconds) || 0)),
      }))
      .slice(0, 5),
  };
}

async function inspectPreviewPage(page: Page): Promise<PreviewAgentElement[]> {
  return page.evaluate(() => {
    const elements = Array.from(document.querySelectorAll(
      "button, a, input, textarea, select, [role=button]",
    )).slice(0, 80) as any[];
    return elements.map((element, id) => {
      const item = element as any;
      item.setAttribute("data-jarvis-agent-id", String(id));
      return {
        id,
        tag: item.tagName.toLowerCase(),
        text: (item.innerText || item.textContent || "").replace(/\\s+/g, " ").trim().slice(0, 180),
        ariaLabel: item.getAttribute("aria-label") || "",
        placeholder: item.getAttribute("placeholder") || "",
        inputType: item.getAttribute("type") || "",
        href: item.tagName.toLowerCase() === "a" ? item.getAttribute("href") || "" : "",
        disabled: item.disabled === true,
      };
    });
  });
}

async function runPreviewAgentAction(page: Page, action: PreviewAgentAction): Promise<string> {
  if (action.action === "wait") {
    await new Promise((resolve) => setTimeout(resolve, action.milliseconds ?? 300));
    return `waited ${action.milliseconds ?? 300}ms`;
  }
  if (action.action === "done") return "finished";
  if (!Number.isInteger(action.id) || (action.id ?? -1) < 0 || (action.id ?? -1) >= 80) {
    throw new Error("The agent selected an invalid element");
  }
  const selector = `[data-jarvis-agent-id="${action.id}"]`;
  if (action.action === "click") {
    await page.$eval(selector, (element: any) => element.click());
    await new Promise((resolve) => setTimeout(resolve, 350));
    return `clicked element ${action.id}`;
  }
  if (action.action === "type") {
    const text = action.text ?? "";
    await page.$eval(selector, (element: any, value) => {
      const input = element as any;
      const setter = Object.getOwnPropertyDescriptor(Object.getPrototypeOf(input), "value")?.set;
      setter?.call(input, value);
      input.dispatchEvent(new Event("input", { bubbles: true }));
      input.dispatchEvent(new Event("change", { bubbles: true }));
    }, text);
    return `typed into element ${action.id}`;
  }
  if (action.action === "select") {
    await page.select(selector, action.value ?? "");
    return `selected a value in element ${action.id}`;
  }
  if (action.action === "press") {
    await page.focus(selector);
    await page.keyboard.press((action.key || "Enter") as any);
    await new Promise((resolve) => setTimeout(resolve, 350));
    return `pressed ${action.key || "Enter"}`;
  }
  throw new Error(`Unsupported preview action: ${action.action}`);
}

/** Run the preview agent toward a goal; returns structured result for the agent loop. */
async function runPreviewAgentGoal(
  goal: string,
  workspaceId: string,
  sessionId: string,
  port: number,
  maxSteps: number,
): Promise<{ completed: boolean; summary: string; events: Array<{ message: string }>; consoleErrors: string[] }> {
  const events: Array<{ message: string }> = [];
  const consoleErrors: string[] = [];
  let page: Page | null = null;
  try {
    const browser = await getScreenshotBrowser();
    page = await browser.newPage();
    await page.setViewport({ width: 1280, height: 900, deviceScaleFactor: 1 });
    await page.setRequestInterception(true);
    page.on("request", (request) => {
      try {
        const requestUrl = request.url();
        const parsed = new URL(requestUrl);
        if (request.isNavigationRequest() && request.frame() === page?.mainFrame() && !localPreviewUrl(requestUrl, port)) {
          void request.abort();
          return;
        }
      } catch {
        void request.abort();
        return;
      }
      void request.continue();
    });
    page.on("console", (message) => {
      if (message.type() === "error") consoleErrors.push(message.text().slice(0, 500));
    });
    page.on("pageerror", (error: any) => consoleErrors.push(String(error?.message ?? error).slice(0, 500)));
    const url = `http://127.0.0.1:${port}`;
    await page.goto(url, { waitUntil: "domcontentloaded", timeout: 20_000 });
    events.push({ message: "Opened the local preview and inspected its interactive elements." });

    let summary = "The agent stopped before completing the goal.";
    let completed = false;
    for (let step = 1; step <= maxSteps; step += 1) {
      const elements = await inspectPreviewPage(page);
      const decisionPrompt = [
        `Goal: ${goal}`,
        `Step: ${step} of ${maxSteps}`,
        `Interactive elements (use the numeric id, never invent selectors): ${JSON.stringify(elements)}`,
        `Recent browser console errors: ${JSON.stringify(consoleErrors.slice(-8))}`,
        "Choose the next smallest useful action. Return JSON only: {done:boolean,message:string,actions:[{action:'click'|'type'|'select'|'press'|'wait'|'done',id?,text?,value?,key?,milliseconds?}]}",
        "Use type only for visible text inputs, never password fields. Use click for buttons and submit controls. Stop with done true when the goal is satisfied or cannot be safely completed.",
      ].join("\n");
      const completion = await pooledClient().chat.completions.create({
        model: jarvisConfig.llmModel,
        messages: [
          {
            role: "system",
            content: withExtraBuildInstructions(
              "You control a website preview inside a local IDE. You must reason from the supplied element inventory, act only on the local page, and never claim success without checking the resulting state. Return valid JSON only. Never use the em dash character.",
              "",
            ),
          },
          { role: "user", content: decisionPrompt },
        ],
        temperature: 0.1,
        max_tokens: 700,
      });
      const decision = parsePreviewAgentDecision(completion.choices[0]?.message?.content?.trim() ?? "");
      if (!decision) {
        summary = "Jarvis could not produce a valid browser action plan.";
        events.push({ message: summary });
        break;
      }
      summary = decision.message || summary;
      events.push({ message: decision.message || `Planning step ${step}.` });
      if (decision.done || decision.actions.length === 0) {
        completed = decision.done;
        break;
      }
      for (const action of decision.actions) {
        if (action.action === "done") {
          completed = true;
          break;
        }
        try {
          const message = await runPreviewAgentAction(page, action);
          events.push({ message });
        } catch (error) {
          const message = error instanceof Error ? error.message : "Browser action failed";
          events.push({ message });
        }
      }
      if (completed) break;
    }
    events.push({ message: completed ? "The browser goal was completed." : summary });
    return { completed, summary, events, consoleErrors };
  } catch (error) {
    const message = error instanceof Error ? error.message : "Preview agent failed";
    events.push({ message });
    return { completed: false, summary: message, events, consoleErrors };
  } finally {
    await page?.close().catch(() => undefined);
  }
}

/** Capture a PNG of the running preview and persist it to the Gallery store. */
type ScreenshotViewport = "desktop" | "mobile";

const screenshotViewportSizes: Record<ScreenshotViewport, { width: number; height: number }> = {
  desktop: { width: 1440, height: 900 },
  mobile: { width: 390, height: 844 },
};

async function capturePreviewPng(
  url: string,
  workspaceId: string,
  viewport: ScreenshotViewport = "desktop",
): Promise<{ url: string; dataUrl: string } | null> {
  try {
    const browser = await getScreenshotBrowser();
    const page: Page = await browser.newPage();
    try {
      const size = screenshotViewportSizes[viewport];
      await page.setViewport({ ...size, deviceScaleFactor: 1 });
      await page.goto(url, { waitUntil: "networkidle0", timeout: 20_000 });
      await new Promise((resolve) => setTimeout(resolve, 700));
      const shot = await page.screenshot({ type: "png" });
      const png = Buffer.from(shot);
      const stored = await persistFile({
        data: png,
        mimeType: "image/png",
        name: `build-preview-${workspaceId}-${viewport}.png`,
        kind: "image",
        owner: "user",
      });
      return {
        url: stored?.url ?? "",
        dataUrl: `data:image/png;base64,${png.toString("base64")}`,
      };
    } finally {
      await page.close();
    }
  } catch (err) {
    console.error("[build] screenshot failed:", err instanceof Error ? err.message : err);
    return null;
  }
}

/** Find the running preview entry for a workspace, if any. */
function findPreview(workspaceId: string, sessionId: string): { child: ChildProcess; port: number; command: string; output: string } | undefined {
  return previewProcesses.get(previewKey(workspaceId, sessionId));
}

/** Build a live preview URL for a workspace, or null when the workspace has no preview yet. */
function previewUrlFor(workspaceId: string, sessionId: string, port?: number | null): string | null {
  const preview = findPreview(workspaceId, sessionId);
  const p = port ?? preview?.port;
  if (!p || !Number.isInteger(p) || p < 1 || p > 65535) return null;
  return `http://127.0.0.1:${p}`;
}
const MAX_ENV_KEYS = 80;
const MAX_ENV_VALUE = 4000;

function cleanText(value: unknown, max: number): string {
  return typeof value === "string" ? value.trim().slice(0, max) : "";
}

function withExtraBuildInstructions(basePrompt: string, extraPrompt: string): string {
  const extra = cleanText(extraPrompt, 4000);
  if (!extra) return basePrompt;
  return `${basePrompt}\n\nAdditional Jarvis Build instructions from the user (additive only; preserve the original Jarvis Build requirements and safety rules):\n${extra}`;
}

function safeWorkspacePath(relPath: string, workspaceId = "default"): string | null {
  const root = getWorkspaceRoot(workspaceId);
  const target = path.resolve(root, relPath);
  return target.startsWith(`${root}${path.sep}`) ? target : null;
}

async function readWorkspaceEnv(workspaceId = "default"): Promise<Record<string, string>> {
  try {
    const content = await fs.readFile(path.join(getWorkspaceRoot(workspaceId), ".jarvis.env.json"), "utf8");
    const parsed = JSON.parse(content) as unknown;
    if (!parsed || typeof parsed !== "object") return {};
    return Object.fromEntries(Object.entries(parsed as Record<string, unknown>)
      .filter(([key, value]) => /^[A-Z][A-Z0-9_]{0,63}$/.test(key) && typeof value === "string")
      .slice(0, MAX_ENV_KEYS)
      .map(([key, value]) => [key, String(value).slice(0, MAX_ENV_VALUE)]));
  } catch {
    return {};
  }
}

async function writeWorkspaceEnv(env: Record<string, string>, workspaceId = "default"): Promise<void> {
  await ensureWorkspace(workspaceId);
  await fs.writeFile(path.join(getWorkspaceRoot(workspaceId), ".jarvis.env.json"), JSON.stringify(env, null, 2), "utf8");
}

function serializeSavedApp(row: typeof buildApps.$inferSelect) {
  return { ...row, metadata: row.metadata ?? {} };
}

router.get("/build/apps", async (req, res) => {
  try {
    const rows = await db.select().from(buildApps).orderBy(desc(buildApps.updatedAt));
    res.json(rows.map(serializeSavedApp));
  } catch (err) {
    req.log.error({ err }, "Failed to list build apps");
    res.status(500).json({ error: "Failed to list build apps" });
  }
});

router.post("/build/apps", async (req, res) => {
  const name = cleanText(req.body?.name, 100) || "Untitled build";
  const description = cleanText(req.body?.description, 500);
  const metadata = {
    runCommand: cleanText(req.body?.runCommand, 400),
    previewPort: Number.isInteger(req.body?.previewPort) ? req.body.previewPort : null,
    savedAt: new Date().toISOString(),
  };
  try {
    const workspaceId = cleanText(req.body?.workspaceId, 64) || "default";
    await ensureWorkspace(workspaceId);
    const filesSnapshot = await listWorkspaceFiles(workspaceId);
    const contents: Record<string, string> = {};
    for (const entry of filesSnapshot) {
      if (entry.type !== "file" || entry.path === ".jarvis.env.json") continue;
      const result = await readWorkspaceFile(entry.path, 200_000, workspaceId);
      if (result.ok) contents[entry.path] = result.content;
    }
    const env = await readWorkspaceEnv(workspaceId);
    const manifest = Buffer.from(JSON.stringify({ version: 1, files: contents, env }, null, 2), "utf8");
    const stored = await persistFile({
      data: manifest,
      mimeType: "application/json",
      name: `${name.replace(/[^a-z0-9]+/gi, "-").toLowerCase()}.jarvis-build.json`,
      kind: "build-app",
      owner: "user",
    });
    if (!stored) {
      res.status(500).json({ error: "Could not persist the build snapshot" });
      return;
    }
    const [row] = await db.insert(buildApps).values({
      name,
      description,
      fileId: stored.fileId,
      metadata: { ...metadata, storageKey: stored.key, fileCount: Object.keys(contents).length, envKeys: Object.keys(env) },
    }).returning();
    res.status(201).json(serializeSavedApp(row));
  } catch (err) {
    req.log.error({ err }, "Failed to save build app");
    res.status(500).json({ error: "Failed to save build app" });
  }
});

router.post("/build/apps/:id/restore", async (req, res) => {
  try {
    const [app] = await db.select().from(buildApps).where(eq(buildApps.id, req.params.id));
    const metadata = (app?.metadata ?? {}) as { storageKey?: string };
    if (!app || !metadata.storageKey) {
      res.status(404).json({ error: "Saved build app not found" });
      return;
    }
    const blob = await getStorage().get(metadata.storageKey);
    if (!blob) {
      res.status(404).json({ error: "Saved build snapshot is unavailable" });
      return;
    }
    const snapshot = JSON.parse(blob.data.toString("utf8")) as { files?: Record<string, string>; env?: Record<string, string> };
    for (const [filePath, content] of Object.entries(snapshot.files ?? {})) {
      if (!safeWorkspacePath(filePath, cleanText(req.body?.workspaceId, 64) || "default")) continue;
      await writeWorkspaceFile(filePath, typeof content === "string" ? content : "", cleanText(req.body?.workspaceId, 64) || "default");
    }
    await writeWorkspaceEnv(snapshot.env ?? {}, cleanText(req.body?.workspaceId, 64) || "default");
    await db.update(buildApps).set({ updatedAt: new Date() }).where(eq(buildApps.id, app.id));
    res.json({ ok: true, restoredFiles: Object.keys(snapshot.files ?? {}).length });
  } catch (err) {
    req.log.error({ err }, "Failed to restore build app");
    res.status(500).json({ error: "Failed to restore build app" });
  }
});

router.get("/build/env", async (req, res) => {
  const workspaceId = cleanText(req.query.workspaceId, 64) || "default";
  res.json({ workspaceId, env: await readWorkspaceEnv(workspaceId) });
});

router.put("/build/env", async (req, res) => {
  const raw = req.body?.env;
  if (!raw || typeof raw !== "object" || Array.isArray(raw)) {
    res.status(400).json({ error: "env must be an object" });
    return;
  }
  const env = Object.fromEntries(Object.entries(raw as Record<string, unknown>)
    .filter(([key, value]) => /^[A-Z][A-Z0-9_]{0,63}$/.test(key) && typeof value === "string")
    .slice(0, MAX_ENV_KEYS)
    .map(([key, value]) => [key, String(value).slice(0, MAX_ENV_VALUE)]));
  await writeWorkspaceEnv(env, cleanText(req.body?.workspaceId, 64) || "default");
  res.json({ env });
});

router.post("/build/ask", async (req, res) => {
  const prompt = cleanText(req.body?.prompt, 300).toLowerCase();
  const inventory = [
    { key: "interface", label: "Professional responsive interface", selected: true },
    { key: "runtime", label: "Local runnable preview", selected: true },
    { key: "accessibility", label: "Accessibility pass", selected: /accessib|a11y|keyboard|screen reader/.test(prompt) },
    { key: "data", label: "Local data or persistence", selected: /database|data|storage|save|persist|crud/.test(prompt) },
    { key: "auth", label: "Local authentication flow", selected: /auth|login|log in|sign up|account|password/.test(prompt) },
    { key: "ai", label: "AI interaction surface", selected: /\bai\b|assistant|chat|llm|model|generate/.test(prompt) },
    { key: "mobile", label: "Mobile responsive layout", selected: /mobile|responsive|phone|tablet/.test(prompt) },
  ];
  res.json({
    inventory,
    questions: [
      { key: "appType", label: "What kind of app is this?", options: ["Landing page", "Dashboard", "Portfolio", "Game", "Tool or utility"] },
      { key: "uiStyle", label: "What UI style do you prefer?", options: ["Dark and futuristic", "Clean and minimal", "Colorful and playful", "Glassmorphism", "Retro or vintage"] },
      { key: "aiProvider", label: "Will it talk to an AI provider?", options: ["No AI needed", "OpenAI-compatible API", "Simple local demo"] },
      { key: "scope", label: "How big should the first version be?", options: ["Single page", "Two or three sections", "Multi-page feel"] },
    ],
  });
});

router.post("/build/plan", async (req, res) => {
  const workspaceId = cleanText(req.body?.workspaceId, 64) || "default";
  const prompt = cleanText(req.body?.prompt, 300);
  const extraSystemPrompt = cleanText(req.body?.extraSystemPrompt, 4000);
  const rawAnswers = req.body?.answers && typeof req.body.answers === "object" && !Array.isArray(req.body.answers)
    ? req.body.answers as Record<string, unknown>
    : {};
  const answers = Object.fromEntries(Object.entries(rawAnswers)
    .map(([key, value]) => [key, cleanText(value, 200)])
    .filter(([, value]) => value));
  if (!prompt) {
    res.status(400).json({ error: "A build request is required" });
    return;
  }
  try {
    await ensureWorkspace(workspaceId);
    const existingFiles = (await listWorkspaceFiles(workspaceId))
      .filter((entry) => entry.type === "file" && !/^\\.?env/i.test(entry.path))
      .map((entry) => entry.path)
      .slice(0, 120);
    const plan = await createBuildPlan(prompt, answers, existingFiles, extraSystemPrompt);
    res.json({ ok: true, plan });
  } catch (err) {
    req.log.error({ err }, "Failed to create Jarvis Build plan");
    res.status(500).json({ error: "Could not create a Jarvis Build plan" });
  }
});

router.post("/build/scaffold", async (req, res) => {
  const workspaceId = cleanText(req.body?.workspaceId, 64) || "default";
  const prompt = cleanText(req.body?.prompt, 300) || "a simple Jarvis starter app";
  const rawAnswers = (req.body?.answers && typeof req.body.answers === "object" && !Array.isArray(req.body.answers))
    ? req.body.answers as Record<string, unknown>
    : {};
  const answers: Record<string, string> = {};
  for (const [key, value] of Object.entries(rawAnswers)) {
    const cleaned = cleanText(value, 200);
    if (key.length <= 100 && cleaned) answers[key] = cleaned;
  }
  const feedback = cleanText(req.body?.feedback, 2000) || null;
  const extraSystemPrompt = cleanText(req.body?.extraSystemPrompt, 4000);
  const rawPlan = req.body?.plan;
  const plan = rawPlan && typeof rawPlan === "object" && !Array.isArray(rawPlan)
    ? parseBuildPlan(JSON.stringify(rawPlan), prompt, [])
    : null;
  try {
    await ensureWorkspace(workspaceId);
    const existingFiles = (await listWorkspaceFiles(workspaceId))
      .filter((entry) => entry.type === "file")
      .map((entry) => entry.path);
    const files = await generateStarterFiles(prompt, answers, feedback, existingFiles, extraSystemPrompt, plan);
    for (const [relPath, content] of Object.entries(files)) {
      if (!safeWorkspacePath(relPath, workspaceId)) continue;
      await writeWorkspaceFile(relPath, content, workspaceId);
    }
    res.status(201).json({ ok: true, files: Object.keys(files), runtime: "static", previewCommand: "python3 -m http.server ${PORT}" });
  } catch (err) {
    req.log.error({ err }, "Failed to scaffold starter");
    res.status(500).json({ error: "Could not scaffold starter" });
  }
});

router.post("/build/iterate", async (req, res) => {
  const workspaceId = cleanText(req.body?.workspaceId, 64) || "default";
  const prompt = cleanText(req.body?.prompt, 300) || "a simple Jarvis starter app";
  const previewOutput = cleanText(req.body?.previewOutput, 6000);
  const extraSystemPrompt = cleanText(req.body?.extraSystemPrompt, 4000);
  const rawPlan = req.body?.plan;
  const plan = rawPlan && typeof rawPlan === "object" && !Array.isArray(rawPlan)
    ? parseBuildPlan(JSON.stringify(rawPlan), prompt, [])
    : null;
  // Allow unlimited iterations (cap at 100 to prevent runaway loops, but this is a soft limit)
  const passNumber = Math.max(1, Number(req.body?.passNumber) || 1);
  const rawAnswers = req.body?.answers && typeof req.body.answers === "object" && !Array.isArray(req.body.answers)
    ? req.body.answers as Record<string, unknown>
    : {};
  const answers = Object.fromEntries(Object.entries(rawAnswers)
    .map(([key, value]) => [key, cleanText(value, 200)])
    .filter(([, value]) => value));
  try {
    await ensureWorkspace(workspaceId);
    // If passNumber exceeds 100, warn but allow the iteration
    if (passNumber > 100) {
      req.log.warn({ workspaceId, passNumber }, "Iteration count is very high, possibly infinite loop");
    }
    const result = await reviewAndFixWorkspace(prompt, answers, workspaceId, previewOutput, passNumber, extraSystemPrompt, plan);
    res.json({ ok: true, passNumber, ...result });
  } catch (err) {
    req.log.error({ err }, "Build self-review failed");
    res.status(500).json({ error: "Build self-review failed" });
  }
});

router.post("/build/preview/agent", async (req, res) => {
  const sessionId = cleanText(req.body?.sessionId, 100) || "studio-preview";
  const workspaceId = cleanText(req.body?.workspaceId, 64) || "default";
  const goal = cleanText(req.body?.goal, 1200);
  const port = Number(req.body?.port);
  const maxSteps = Math.min(10, Math.max(1, Number(req.body?.maxSteps) || 6));
  const extraSystemPrompt = cleanText(req.body?.extraSystemPrompt, 4000);
  const preview = findPreview(workspaceId, sessionId);
  if (!goal) {
    res.status(400).json({ error: "A goal is required" });
    return;
  }
  if (!preview || preview.port !== port || !Number.isInteger(port) || port < 1024 || port > 65535) {
    res.status(400).json({ error: "Start the local preview before asking Jarvis to interact with it" });
    return;
  }

  const events: Array<{ type: "inspect" | "decision" | "action" | "error" | "complete"; message: string; step?: number }> = [];
  const consoleErrors: string[] = [];
  let page: Page | null = null;
  try {
    const browser = await getScreenshotBrowser();
    page = await browser.newPage();
    await page.setViewport({ width: 1280, height: 900, deviceScaleFactor: 1 });
    await page.setRequestInterception(true);
    page.on("request", (request) => {
      try {
        const requestUrl = request.url();
        const parsed = new URL(requestUrl);
        if (request.isNavigationRequest() && request.frame() === page?.mainFrame() && !localPreviewUrl(requestUrl, port)) {
          void request.abort();
          return;
        }
      } catch {
        void request.abort();
        return;
      }
      void request.continue();
    });
    page.on("console", (message) => {
      if (message.type() === "error") consoleErrors.push(message.text().slice(0, 500));
    });
    page.on("pageerror", (error: any) => consoleErrors.push(String(error?.message ?? error).slice(0, 500)));
    const url = `http://127.0.0.1:${port}`;
    await page.goto(url, { waitUntil: "domcontentloaded", timeout: 20_000 });
    events.push({ type: "inspect", message: "Opened the local preview and inspected its interactive elements." });

    let summary = "The agent stopped before completing the goal.";
    let completed = false;
    for (let step = 1; step <= maxSteps; step += 1) {
      const elements = await inspectPreviewPage(page);
      const decisionPrompt = [
        `Goal: ${goal}`,
        `Step: ${step} of ${maxSteps}`,
        `Interactive elements (use the numeric id, never invent selectors): ${JSON.stringify(elements)}`,
        `Recent browser console errors: ${JSON.stringify(consoleErrors.slice(-8))}`,
        "Choose the next smallest useful action. Return JSON only: {done:boolean,message:string,actions:[{action:'click'|'type'|'select'|'press'|'wait'|'done',id?,text?,value?,key?,milliseconds?}]}",
        "Use type only for visible text inputs, never password fields. Use click for buttons and submit controls. Stop with done true when the goal is satisfied or cannot be safely completed.",
      ].join("\\n");
      const completion = await pooledClient().chat.completions.create({
        model: jarvisConfig.llmModel,
        messages: [
          {
            role: "system",
            content: withExtraBuildInstructions(
              "You control a website preview inside a local IDE. You must reason from the supplied element inventory, act only on the local page, and never claim success without checking the resulting state. Return valid JSON only. Never use the em dash character.",
              extraSystemPrompt,
            ),
          },
          { role: "user", content: decisionPrompt },
        ],
        temperature: 0.1,
        max_tokens: 700,
      });
      const decision = parsePreviewAgentDecision(completion.choices[0]?.message?.content?.trim() ?? "");
      if (!decision) {
        summary = "Jarvis could not produce a valid browser action plan.";
        events.push({ type: "error", step, message: summary });
        break;
      }
      summary = decision.message || summary;
      events.push({ type: "decision", step, message: decision.message || `Planning step ${step}.` });
      if (decision.done || decision.actions.length === 0) {
        completed = decision.done;
        break;
      }
      for (const action of decision.actions) {
        if (action.action === "done") {
          completed = true;
          break;
        }
        try {
          const message = await runPreviewAgentAction(page, action);
          events.push({ type: "action", step, message });
        } catch (error) {
          const message = error instanceof Error ? error.message : "Browser action failed";
          events.push({ type: "error", step, message });
        }
      }
      if (completed) break;
    }
    events.push({ type: "complete", message: completed ? "The browser goal was completed." : summary });
    res.json({ ok: true, completed, summary, events, consoleErrors: [...new Set(consoleErrors)].slice(-12), elements: page ? await inspectPreviewPage(page) : [] });
  } catch (error) {
    const message = error instanceof Error ? error.message : "Preview agent failed";
    events.push({ type: "error", message });
    res.status(500).json({ error: message, events, consoleErrors: [...new Set(consoleErrors)].slice(-12) });
  } finally {
    await page?.close().catch(() => undefined);
  }
});

router.post("/build/walkthrough", async (req, res) => {
  const workspaceId = cleanText(req.body?.workspaceId, 64) || "default";
  const sessionId = cleanText(req.body?.sessionId, 100) || "studio-preview";
  const port = Number(req.body?.port);
  const preview = findPreview(workspaceId, sessionId);
  if (!preview || preview.port !== port || !Number.isInteger(port) || port < 1024 || port > 65535) {
    res.status(400).json({ error: "Start the local preview before running a walkthrough" });
    return;
  }

  const errors: string[] = [];
  const screenshotKeys: string[] = [];
  let page: Page | null = null;
  try {
    const browser = await getScreenshotBrowser();
    page = await browser.newPage();
    await page.setViewport({ width: 1440, height: 900, deviceScaleFactor: 1 });
    await page.setRequestInterception(true);
    page.on("request", (request) => {
      try {
        const requestUrl = request.url();
        if (request.isNavigationRequest() && request.frame() === page?.mainFrame() && !localPreviewUrl(requestUrl, port)) {
          void request.abort();
          return;
        }
      } catch {
        void request.abort();
        return;
      }
      void request.continue();
    });
    page.on("console", (message) => {
      if (message.type() === "error") errors.push(`Console error: ${message.text().slice(0, 500)}`);
    });
    page.on("pageerror", (error: Error) => errors.push(`Page error: ${error.message.slice(0, 500)}`));
    page.on("requestfailed", (request) => errors.push(`Request failed: ${request.method()} ${request.url().slice(0, 300)} (${request.failure()?.errorText ?? "unknown"})`));
    await page.goto(`http://127.0.0.1:${port}`, { waitUntil: "domcontentloaded", timeout: 20_000 });

    const screenshot = await page.screenshot({ type: "png" });
    const stored = await persistFile({ data: Buffer.from(screenshot), mimeType: "image/png", name: `walkthrough-${workspaceId}-${Date.now()}.png`, kind: "image", owner: "user" });
    if (stored?.url) screenshotKeys.push(stored.url);

    const elements: Array<{ index: number; tag: string; text: string; disabled: boolean; href: string }> = await page.evaluate(() => {
      const nodes = Array.from(document.querySelectorAll("button, a, input, textarea, select, [role=button]")) as Array<any>;
      return nodes.map((element, index) => {
        element.setAttribute("data-jarvis-walkthrough-id", String(index));
        return {
          index,
          tag: String(element.tagName).toLowerCase(),
          text: String(element.textContent ?? "").replace(/\\s+/g, " ").trim().slice(0, 160),
          disabled: element.disabled === true,
          href: String(element.tagName).toLowerCase() === "a" ? String(element.getAttribute("href") ?? "") : "",
        };
      }).slice(0, 120);
    });

    for (const element of elements) {
      if (element.disabled || element.href && !element.href.startsWith("#")) continue;
      try {
        await page.$eval(`[data-jarvis-walkthrough-id="${element.index}"]`, (node) => {
          const tag = node.tagName.toLowerCase();
          if (tag === "input" || tag === "textarea" || tag === "select") return;
          (node as any).click();
        });
        await new Promise((resolve) => setTimeout(resolve, 140));
      } catch (error) {
        errors.push(`Interactive element ${element.index} (${element.tag} ${element.text || "untitled"}) failed: ${error instanceof Error ? error.message : "click failed"}`);
      }
    }

    const reportPath = path.join(WORKSPACE_ROOT, "full-walktrough.md");
    const timestamp = new Date().toISOString().replace("T", " ").replace("Z", " UTC");
    const uniqueErrors = [...new Set(errors)];
    const lines = [
      "",
      "--------------------------------------------------",
      `WALKTHROUGH SESSION START: ${timestamp}`,
      "--------------------------------------------------",
      ...uniqueErrors.map((error) => `- [ERROR] ${error}`),
      ...(uniqueErrors.length === 0 ? ["- No unexpected interactive errors observed."] : []),
      ...(screenshotKeys.length > 0 ? [`- Screenshot evidence: ${screenshotKeys.join(", ")}`] : []),
      "==================================================",
      "",
    ];
    await ensureWorkspace(workspaceId);
    await fs.appendFile(reportPath, lines.join("\\n"), "utf8");
    res.json({ ok: true, errors: uniqueErrors, reportPath: "full-walktrough.md", screenshotUrls: screenshotKeys, testedElements: elements.length });
  } catch (error) {
    const message = error instanceof Error ? error.message : "Walkthrough failed";
    res.status(500).json({ error: message, errors });
  } finally {
    await page?.close().catch(() => undefined);
  }
});

router.post("/build/screenshot", async (req, res) => {
  const sessionId = cleanText(req.body?.sessionId, 100) || "studio-preview";
  const workspaceId = cleanText(req.body?.workspaceId, 64) || "default";
  const requestedUrl = cleanText(req.body?.url, 500);
  const url = requestedUrl && /^https?:\/\/(localhost|127\.0\.0\.1)(:\d+)?(\/|$)/i.test(requestedUrl)
    ? requestedUrl
    : previewUrlFor(workspaceId, sessionId, Number.isInteger(req.body?.port) ? Number(req.body.port) : null);
  if (!url) {
    res.status(400).json({ error: "No preview is running for this workspace" });
    return;
  }
  const requestedViewports: unknown[] = Array.isArray(req.body?.viewports) ? req.body.viewports : ["desktop"];
  const viewports: ScreenshotViewport[] = [...new Set(
    requestedViewports.filter((value): value is ScreenshotViewport => value === "desktop" || value === "mobile"),
  )];
  if (viewports.length === 0) {
    res.status(400).json({ error: "At least one supported screenshot viewport is required" });
    return;
  }
  const screenshots: Partial<Record<ScreenshotViewport, { url: string; dataUrl: string }>> = {};
  for (const viewport of viewports) {
    const shot = await capturePreviewPng(url, workspaceId, viewport);
    if (!shot) {
      res.status(500).json({ error: `${viewport} screenshot failed, the headless browser is unavailable` });
      return;
    }
    screenshots[viewport] = shot;
  }
  const desktop = screenshots.desktop;
  res.json({ ok: true, url: desktop?.url ?? screenshots.mobile?.url ?? "", dataUrl: desktop?.dataUrl ?? screenshots.mobile?.dataUrl ?? "", screenshots });
});

router.post("/build/preview/start", async (req, res) => {
  const sessionId = cleanText(req.body?.sessionId, 100) || "default";
  const workspaceId = cleanText(req.body?.workspaceId, 64) || "default";
  const command = cleanText(req.body?.command, 500);
  const port = Number(req.body?.port);
  if (!command || !Number.isInteger(port) || port < 1024 || port > 65535) {
    res.status(400).json({ error: "A command and valid preview port (1024-65535) are required" });
    return;
  }
  await ensureWorkspace(workspaceId);
  const key = previewKey(workspaceId, sessionId);
  const previous = previewProcesses.get(key);
  previous?.child.kill("SIGTERM");
  const env = await readWorkspaceEnv(workspaceId);
  const child = spawn("/bin/bash", ["-lc", command], {
    cwd: getSessionCwd(sessionId, workspaceId),
    env: getWorkspaceCommandEnvironment({ ...env, PORT: String(port), HOST: "0.0.0.0" }),
    detached: false,
    stdio: ["ignore", "pipe", "pipe"],
  });
  const entry = { child, port, command, output: "" };
  previewProcesses.set(key, entry);
  const collect = (chunk: Buffer) => { entry.output = `${entry.output}${chunk.toString()}`.slice(-12000); };
  child.stdout?.on("data", collect);
  child.stderr?.on("data", collect);
  child.on("exit", () => { if (previewProcesses.get(key)?.child === child) previewProcesses.delete(key); });
  res.status(201).json({ sessionId, workspaceId, port, url: `http://localhost:${port}`, running: true });
});

router.post("/build/preview/stop", async (req, res) => {
  const sessionId = cleanText(req.body?.sessionId, 100) || "default";
  const workspaceId = cleanText(req.body?.workspaceId, 64) || "default";
  const entry = previewProcesses.get(previewKey(workspaceId, sessionId));
  if (entry) {
    entry.child.kill("SIGTERM");
    previewProcesses.delete(previewKey(workspaceId, sessionId));
  }
  res.json({ ok: true });
});

router.get("/build/preview/status", async (req, res) => {
  const sessionId = cleanText(req.query.sessionId, 100) || "default";
  const workspaceId = cleanText(req.query.workspaceId, 64) || "default";
  const entry = previewProcesses.get(previewKey(workspaceId, sessionId));
  res.json(entry ? { running: true, workspaceId, port: entry.port, command: entry.command, output: entry.output.slice(-4000) } : { running: false, workspaceId });
});

/**
 * ─────────────────────────────────────────────────────────────────────────
 * AUTONOMOUS BUILD AGENT
 * ─────────────────────────────────────────────────────────────────────────
 * A genuine agentic coding loop. Instead of one-shot "generate every file"
 * then a reviewer, Jarvis now:
 *   1. plans the work from the request + an inventory of the workspace,
 *   2. repeatedly asks the LLM to emit ONE tool call,
 *   3. executes that tool against real primitives (filesystem, terminal,
 *      preview, browser, tests, search, git),
 *   4. returns the observation to the model,
 *   5. continues until the model signals "done" or a bounded step budget
 *      is exhausted, then runs a final verification pass.
 *
 * Every tool reuses existing, already-audited primitives from workspace.ts,
 * build.ts (preview/screenshot/browser), search.ts, and the sibling routes.
 * Nothing here duplicates existing functionality; it orchestrates it.
 */

type AgentToolName =
  | "list_files"
  | "read_file"
  | "write_file"
  | "patch_file"
  | "rename_file"
  | "delete_file"
  | "run_terminal"
  | "search_files"
  | "replace_in_files"
  | "preview_screenshot"
  | "browser_action"
  | "run_tests"
  | "verify_claim"
  | "git_status"
  | "think"
  | "done";

interface AgentToolCall {
  tool: AgentToolName;
  reason?: string;
  path?: string;
  content?: string;
  search?: string;
  replacement?: string;
  command?: string;
  viewport?: "desktop" | "mobile";
  goal?: string;
  maxSteps?: number;
  text?: string;
  value?: string;
  key?: string;
  query?: string;
  claim?: string;
  workspace?: string;
}

interface AgentStep {
  step: number;
  tool: AgentToolName;
  reason: string;
  observation: string;
  ok: boolean;
}

interface AgentEvent {
  type: "plan" | "tool" | "observation" | "verify" | "done" | "error";
  step?: number;
  tool?: string;
  message: string;
  detail?: string;
}

/** Bounded, agent-side tool protocol for the autonomous build loop. */
const AGENT_TOOL_SCHEMA = `You are an autonomous coding agent inside Jarvis Build. On EVERY turn you MUST emit exactly one tool call as a JSON object (no prose before or after) of this shape:
{"tool":"<name>","reason":"<one short sentence why>","...args"}
Allowed tools and their args:
- list_files — list the workspace tree.
- read_file {path} — read a file's content.
- write_file {path,content} — create/overwrite a file.
- patch_file {path,search:"<exact existing text to replace>",replacement:"<new text>"} — surgically edit a file. The search must appear verbatim in the file; if it does not, the call fails and you must re-read and retry with the correct text.
- rename_file {path,newPath} — rename/move a file.
- delete_file {path} — delete a file.
- run_terminal {command} — run one shell command in the workspace (capped, sandboxed). Use it for installs, builds, linters, and app commands.
- search_files {query,regex?,caseSensitive?} — grep the workspace.
- replace_in_files {search,replacement,regex?,caseSensitive?,files?} — replace text across files.
- preview_screenshot {viewport?:"desktop"|"mobile"} — capture a PNG of the running local preview (start the preview first via run_terminal).
- browser_action {goal,maxSteps?} — drive the live preview like a user (click/type/navigate) to test behavior.
- run_tests {command?} — run the project test command (auto-detected if omitted).
- verify_claim {claim} — check a factual claim against the live web (Tavily) when correctness depends on external facts.
- git_status — show the workspace git status.
- think {reason:"<internal note>"} — when you need to reason before acting (emits no side effect).
- done {"summary":"<what you built and verified>"} — ONLY when the request is fully implemented AND verified (preview works, no runtime errors). Never finish early.
Rules: inspect before editing, edit precisely (prefer patch_file over write_file), run_terminal to install/build/test, verify visually with preview_screenshot or behaviorally with browser_action, and loop until done. NEVER use the em dash character. Keep reason <= 160 chars.`;

/** Parse one agent tool call, tolerating markdown fences and stray text. */
function parseAgentToolCall(raw: string): AgentToolCall | null {
  const match = raw.match(/\{[\s\S]*\}/);
  if (!match) return null;
  try {
    const parsed = JSON.parse(match[0]) as Record<string, unknown>;
    const tool = parsed.tool;
    if (typeof tool !== "string" || !/^[a-z_]{3,24}$/.test(tool)) return null;
    const allowed = new Set<AgentToolName>([
      "list_files", "read_file", "write_file", "patch_file", "rename_file", "delete_file",
      "run_terminal", "search_files", "replace_in_files", "preview_screenshot", "browser_action",
      "run_tests", "verify_claim", "git_status", "think", "done",
    ]);
    if (!allowed.has(tool as AgentToolName)) return null;
    return {
      tool: tool as AgentToolName,
      reason: cleanText(parsed.reason, 160),
      path: cleanText(parsed.path, 500),
      content: typeof parsed.content === "string" ? parsed.content.slice(0, 2_000_000) : undefined,
      search: typeof parsed.search === "string" ? parsed.search.slice(0, 100_000) : undefined,
      replacement: typeof parsed.replacement === "string" ? parsed.replacement.slice(0, 100_000) : undefined,
      command: cleanText(parsed.command, 12_000),
      viewport: parsed.viewport === "mobile" ? "mobile" : "desktop",
      goal: cleanText(parsed.goal, 1200),
      maxSteps: Math.min(12, Math.max(1, Number(parsed.maxSteps) || 6)),
      text: cleanText(parsed.text, 2000),
      value: cleanText(parsed.value, 300),
      key: cleanText(parsed.key, 40),
      query: cleanText(parsed.query, 500),
      claim: cleanText(parsed.claim, 2000),
      workspace: cleanText(parsed.workspace, 64),
    };
  } catch {
    return null;
  }
}

/** Verify an exact substring exists in a file; returns the line span for the observation. */
async function verifyPatchTarget(workspaceId: string, relPath: string, search: string): Promise<{ found: boolean; snippet?: string }> {
  const result = await readWorkspaceFile(relPath, 100_000, workspaceId);
  if (!result.ok) return { found: false };
  const idx = result.content.indexOf(search);
  if (idx < 0) return { found: false };
  const before = result.content.slice(Math.max(0, idx - 120), idx);
  const after = result.content.slice(idx + search.length, idx + search.length + 120);
  return { found: true, snippet: `...${before}⟦TARGET⟧${after}...` };
}

/** Execute one agent tool call and return an observation string + ok flag. */
async function executeAgentTool(
  call: AgentToolCall,
  ctx: { workspaceId: string; sessionId: string; prompt: string; answers: Record<string, string> },
  events: AgentEvent[],
): Promise<{ observation: string; ok: boolean }> {
  const { workspaceId, sessionId } = ctx;
  switch (call.tool) {
    case "list_files": {
      const files = (await listWorkspaceFiles(workspaceId)).map((e) => e.path).slice(0, 200);
      return { observation: `Workspace files (${files.length}):\n${files.join("\n") || "(empty)"}`, ok: true };
    }
    case "read_file": {
      if (!call.path) return { observation: "read_file requires {path}.", ok: false };
      const result = await readWorkspaceFile(call.path, 100_000, workspaceId);
      if (!result.ok) return { observation: `Cannot read ${call.path}: ${result.error}`, ok: false };
      return { observation: `=== ${call.path} ===\n${result.content.slice(0, 80_000)}`, ok: true };
    }
    case "write_file": {
      if (!call.path || call.content === undefined) return { observation: "write_file requires {path,content}.", ok: false };
      if (!safeWorkspacePath(call.path, workspaceId)) return { observation: `Path rejected: ${call.path}`, ok: false };
      const result = await writeWorkspaceFile(call.path, call.content, workspaceId);
      return result.ok
        ? { observation: `Wrote ${call.path} (${call.content.length} chars).`, ok: true }
        : { observation: `Write failed: ${result.error}`, ok: false };
    }
    case "patch_file": {
      if (!call.path || call.search === undefined || call.replacement === undefined) {
        return { observation: "patch_file requires {path,search,replacement}.", ok: false };
      }
      // Verify the exact target exists before mutating — this is what makes
      // the agent edit "precisely" rather than blindly.
      const verify = await verifyPatchTarget(workspaceId, call.path, call.search);
      if (!verify.found) {
        return {
          observation: `patch_file aborted: the exact search text was NOT found in ${call.path}. Re-read the file and supply verbatim text. Context near expectation:\n${verify.snippet ?? "(file unreadable/missing)"}`,
          ok: false,
        };
      }
      const current = await readWorkspaceFile(call.path, 2_000_000, workspaceId);
      if (!current.ok) return { observation: `Cannot read ${call.path} to patch.`, ok: false };
      const updated = current.content.replace(call.search, call.replacement);
      if (updated === current.content) return { observation: "patch_file made no change (search not found).", ok: false };
      const written = await writeWorkspaceFile(call.path, updated, workspaceId);
      return written.ok
        ? { observation: `Patched ${call.path} (replaced ${call.search.length} chars).`, ok: true }
        : { observation: `Patch write failed: ${written.error}`, ok: false };
    }
    case "rename_file": {
      if (!call.path || !call.content) {
        // call.path = source, call.content = destination
      }
      const from = call.path ?? "";
      const to = call.content ?? "";
      if (!from || !to) return { observation: "rename_file requires {path,content:newPath}.", ok: false };
      try {
        const res = await renameWorkspacePath(from, to, workspaceId);
        return res.ok ? { observation: `Renamed ${from} → ${to}.`, ok: true } : { observation: `Rename failed: ${res.error}`, ok: false };
      } catch (err) {
        return { observation: `Rename failed: ${err instanceof Error ? err.message : String(err)}`, ok: false };
      }
    }
    case "delete_file": {
      if (!call.path) return { observation: "delete_file requires {path}.", ok: false };
      try {
        await deleteWorkspacePath(call.path, workspaceId);
        return { observation: `Deleted ${call.path}.`, ok: true };
      } catch (err) {
        return { observation: `Delete failed: ${err instanceof Error ? err.message : String(err)}`, ok: false };
      }
    }
    case "run_terminal": {
      if (!call.command) return { observation: "run_terminal requires {command}.", ok: false };
      const run = await runTerminalCommand("default", call.command, { workspaceId, timeoutMs: 60_000 });
      const out = `${run.stdout}${run.stderr}`.slice(-6000);
      const tail = run.timedOut ? "\n[command timed out]" : run.exitCode !== 0 ? `\n[exit ${run.exitCode}]` : "\n[exit 0]";
      return { observation: `Ran: ${call.command}\n${out}${tail}`, ok: run.exitCode === 0 };
    }
    case "search_files": {
      if (!call.query) return { observation: "search_files requires {query}.", ok: false };
      const result = await searchFiles(workspaceId, call.query, {
        regex: call.replacement === "regex",
        caseSensitive: call.workspace === "case",
        maxResults: 60,
      });
      const preview = result.matches.slice(0, 40)
        .map((m) => `${m.file}:${m.line}: ${m.preview.trim()}`)
        .join("\n");
      return {
        observation: `Search "${call.query}" → ${result.totalMatches} matches in ${result.filesWithMatches} files.\n${preview || "(no matches)"}`,
        ok: true,
      };
    }
    case "replace_in_files": {
      if (!call.search || call.replacement === undefined) return { observation: "replace_in_files requires {search,replacement}.", ok: false };
      const files = call.path ? [call.path] : [];
      const result = await replaceInFiles(workspaceId, call.search, call.replacement, {
        regex: call.query === "regex",
        caseSensitive: call.workspace === "case",
        files: files.slice(0, 50),
        maxReplacements: 2000,
      });
      return {
        observation: `Replaced ${result.totalReplaced} occurrence(s) across ${result.filesModified.length} file(s): ${result.filesModified.join(", ") || "(none)"}`,
        ok: result.totalReplaced > 0,
      };
    }
    case "preview_screenshot": {
      const preview = findPreview(workspaceId, sessionId);
      if (!preview) return { observation: "No preview is running. Start one with run_terminal (e.g. `python3 -m http.server ${PORT}` or npm run dev) first.", ok: false };
      const url = `http://127.0.0.1:${preview.port}`;
      const shot = await capturePreviewPng(url, workspaceId, call.viewport ?? "desktop");
      if (!shot) return { observation: "Screenshot failed — headless browser unavailable.", ok: false };
      return { observation: `Captured ${call.viewport ?? "desktop"} preview screenshot. dataUrl length=${shot.dataUrl.length}. Use it to judge layout/visuals.`, ok: true, };
    }
    case "browser_action": {
      if (!call.goal) return { observation: "browser_action requires {goal}.", ok: false };
      const preview = findPreview(workspaceId, sessionId);
      if (!preview) return { observation: "No preview running — start it first.", ok: false };
      const agentRes = await runPreviewAgentGoal(call.goal, workspaceId, sessionId, preview.port, call.maxSteps ?? 6);
      return { observation: `Browser agent: completed=${agentRes.completed}. ${agentRes.summary}\nEvents:\n${agentRes.events.map((e) => `- ${e.message}`).join("\n")}\nConsole errors: ${agentRes.consoleErrors.join(" | ") || "none"}`, ok: agentRes.completed };
    }
    case "run_tests": {
      const command = call.command?.trim() || await detectTestCommand(workspaceId);
      if (!command) return { observation: "No test command detected and none provided.", ok: false };
      const run = await runTerminalCommand("default", command, { workspaceId, timeoutMs: 90_000 });
      const out = `${run.stdout}${run.stderr}`.slice(-6000);
      return { observation: `Tests (${command}):\n${out}\n[exit ${run.exitCode}]`, ok: run.exitCode === 0 };
    }
    case "verify_claim": {
      if (!call.claim) return { observation: "verify_claim requires {claim}.", ok: false };
      const verdict = await verifyClaimAgainstWeb(call.claim);
      return { observation: `verify_claim: ${verdict.verdict}. ${verdict.note}\nSources: ${verdict.sources.join(", ") || "none"}`, ok: verdict.verdict !== "unverifiable" };
    }
    case "git_status": {
      const run = await runTerminalCommand("default", "git status --porcelain --branch 2>/dev/null || echo 'no git repo'", { workspaceId, timeoutMs: 10_000 });
      return { observation: `Git status:\n${run.stdout.slice(-3000) || run.stderr.slice(-1000)}`, ok: true };
    }
    case "think": {
      return { observation: `(thinking noted: ${call.reason ?? "—"})`, ok: true };
    }
    case "done": {
      return { observation: `Agent marked done. Summary: ${call.reason ?? "(none)"}`, ok: true };
    }
    default:
      return { observation: `Unknown tool: ${call.tool}`, ok: false };
  }
}

/** Heuristic test-command detection from workspace files. */
async function detectTestCommand(workspaceId: string): Promise<string | null> {
  const entries = await listWorkspaceFiles(workspaceId);
  const files = entries.map((e) => e.path);
  if (files.includes("package.json")) {
    return "npm test";
  }
  if (files.includes("pytest.ini") || files.includes("pyproject.toml") || files.includes("setup.py") || files.includes("test_requirements.txt")) {
    return "pytest";
  }
  if (files.includes("Cargo.toml")) return "cargo test";
  if (files.includes("go.mod")) return "go test ./...";
  if (files.includes("pom.xml")) return "mvn test";
  return null;
}


async function verifyClaimAgainstWeb(claim: string): Promise<{ verdict: "supported" | "contradicted" | "unverifiable"; note: string; sources: string[] }> {
  const apiKey = process.env["TAVILY_API_KEY"] ?? process.env["WEB_SEARCH_API_KEY"];
  if (!apiKey) return { verdict: "unverifiable", note: "No web search key configured; cannot verify external claims.", sources: [] };
  try {
    const res = await fetch("https://api.tavily.com/search", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ api_key: apiKey, query: claim, search_depth: "basic", max_results: 4 }),
      signal: AbortSignal.timeout(10_000),
    });
    if (!res.ok) return { verdict: "unverifiable", note: "Search request failed.", sources: [] };
    const data = (await res.json()) as { results?: Array<{ url: string; content?: string }> };
    const snippets = (data.results ?? []).map((r) => r.content ?? "").join(" ");
    const sources = (data.results ?? []).map((r) => r.url).slice(0, 3);
    const overlap = claim.toLowerCase().split(/\W+/).filter((w) => w.length > 4)
      .filter((w) => snippets.toLowerCase().includes(w)).length;
    const verdict = overlap >= Math.min(3, Math.ceil(claim.split(/\W+/).filter((w) => w.length > 4).length / 3))
      ? "supported" as const : "unverifiable" as const;
    return { verdict, note: verdict === "supported" ? "Matches published sources." : "Not clearly confirmed by top sources.", sources };
  } catch {
    return { verdict: "unverifiable", note: "Search request errored.", sources: [] };
  }
}

/** Build a compact plan from the request so the first turn has context. */
async function createAgentPlan(prompt: string, answers: Record<string, string>, workspaceId: string): Promise<string> {
  const files = (await listWorkspaceFiles(workspaceId)).map((e) => e.path).slice(0, 60);
  const userSummary = Object.entries(answers).map(([k, v]) => `${k}: ${v}`).join("; ");
  const system = withExtraBuildInstructions(
    "You are the planning layer of the autonomous Jarvis Build agent. Given a request and the current workspace, " +
    "write a short, ordered plan of concrete steps the agent will take (inspect, scaffold/edit, install, run, verify). " +
    "Return ONLY plain text, no JSON, no markdown fences. Never use the em dash character.",
    "",
  );
  try {
    const completion = await pooledClient().chat.completions.create({
      model: jarvisConfig.llmModel,
      messages: [
        { role: "system", content: system },
        { role: "user", content: `Request: ${prompt}\nAnswers: ${userSummary || "(none)"}\nWorkspace: ${files.join(", ") || "(empty)"}` },
      ],
      temperature: 0.2,
      max_tokens: 600,
    });
    return completion.choices[0]?.message?.content?.trim() || `Build: ${prompt}`;
  } catch {
    return `Build: ${prompt}\nWorkspace: ${files.join(", ") || "(empty)"}`;
  }
}

/**
 * POST /build/agent — run the autonomous build loop.
 * Streams progress as Server-Sent Events; final event is {type:"result",...}.
 */
router.post("/build/agent", async (req, res) => {
  const workspaceId = cleanText(req.body?.workspaceId, 64) || "default";
  const sessionId = cleanText(req.body?.sessionId, 100) || "studio-preview";
  const prompt = cleanText(req.body?.prompt, 1200);
  const extraSystemPrompt = cleanText(req.body?.extraSystemPrompt, 4000);
  const rawAnswers = req.body?.answers && typeof req.body.answers === "object" && !Array.isArray(req.body.answers)
    ? req.body.answers as Record<string, unknown>
    : {};
  const answers = Object.fromEntries(Object.entries(rawAnswers).map(([k, v]) => [k, cleanText(v, 200)]).filter(([, v]) => v));
  const maxSteps = Math.min(40, Math.max(4, Number(req.body?.maxSteps) || 24));
  if (!prompt) {
    res.status(400).json({ error: "A build request is required" });
    return;
  }

  // SSE headers
  res.setHeader("Content-Type", "text/event-stream");
  res.setHeader("Cache-Control", "no-cache, no-transform");
  res.setHeader("Connection", "keep-alive");
  res.setHeader("X-Accel-Buffering", "no");
  res.flushHeaders?.();

  const send = (event: AgentEvent | { type: "result"; ok: boolean; summary: string; steps: AgentStep[]; files: string[] }) => {
    res.write(`data: ${JSON.stringify(event)}\n\n`);
  };

  const events: AgentEvent[] = [];
  const steps: AgentStep[] = [];
  const filesTouched = new Set<string>();

  try {
    await ensureWorkspace(workspaceId);
    const plan = await createAgentPlan(prompt, answers, workspaceId);
    events.push({ type: "plan", message: plan });
    send({ type: "plan", message: plan });

    const systemPrompt = withExtraBuildInstructions(AGENT_TOOL_SCHEMA, extraSystemPrompt);
    const history: Array<{ role: "system" | "user" | "assistant"; content: string }> = [
      { role: "system", content: systemPrompt },
      { role: "user", content: `Request: ${prompt}\nAnswers: ${JSON.stringify(answers)}\nPlan:\n${plan}\nBegin. Emit your first tool call as JSON.` },
    ];

    let finished = false;
    let summary = "";
    for (let step = 1; step <= maxSteps && !finished; step += 1) {
      const completion = await pooledClient().chat.completions.create({
        model: jarvisConfig.llmModel,
        messages: history,
        temperature: 0.2,
        max_tokens: 1200,
      });
      const raw = completion.choices[0]?.message?.content?.trim() ?? "";
      const call = parseAgentToolCall(raw);
      if (!call) {
        events.push({ type: "error", step, message: "Model did not return a valid tool call; retrying with a reminder." });
        send({ type: "error", step, message: "Invalid tool call format. Emit exactly one JSON tool call." });
        history.push({ role: "assistant", content: raw });
        history.push({ role: "user", content: "That was not a valid tool call. Respond with exactly one JSON object of the form {\"tool\":\"...\",\"reason\":\"...\", ...}." });
        continue;
      }

      events.push({ type: "tool", step, tool: call.tool, message: call.reason ?? call.tool });
      send({ type: "tool", step, tool: call.tool, message: call.reason ?? call.tool });

      if (call.path) filesTouched.add(call.path);

      const { observation, ok } = await executeAgentTool(call, { workspaceId, sessionId, prompt, answers }, events);
      steps.push({ step, tool: call.tool, reason: call.reason ?? "", observation: observation.slice(0, 800), ok });
      events.push({ type: "observation", step, tool: call.tool, message: observation.slice(0, 600) });
      send({ type: "observation", step, tool: call.tool, message: observation.slice(0, 1000) });

      history.push({ role: "assistant", content: raw });
      history.push({ role: "user", content: `Observation (${ok ? "ok" : "failed"}): ${observation.slice(0, 6000)}\n\nEmit the next tool call as JSON, or {\"tool\":\"done\",\"reason\":\"<summary>\"} when fully implemented and verified.` });

      if (call.tool === "done") {
        finished = true;
        summary = call.reason ?? "Build complete.";
        events.push({ type: "done", step, message: summary });
        send({ type: "done", step, message: summary });
      }
    }

    // Final verification pass — confirm a runnable entry point + sane preview.
    events.push({ type: "verify", message: "Running final verification pass." });
    send({ type: "verify", message: "Running final verification pass." });
    const files = (await listWorkspaceFiles(workspaceId)).map((e) => e.path);
    const hasEntry = files.some((f) => /^index\.(html|js|ts)$/i.test(f) || f === "main.js" || f === "main.tsx" || f === "App.tsx");
    const preview = findPreview(workspaceId, sessionId);
    let verifyNote = hasEntry ? "Entry point present. " : "Warning: no obvious entry point (index.html/main). ";
    if (preview) {
      const shot = await capturePreviewPng(`http://127.0.0.1:${preview.port}`, workspaceId, "desktop");
      verifyNote += shot ? "Preview screenshot captured successfully." : "Preview screenshot failed.";
    } else {
      verifyNote += "No preview running (start one to visually verify).";
    }

    send({
      type: "result",
      ok: finished && hasEntry,
      summary: summary || `Stopped after ${steps.length} steps. ${verifyNote}`,
      steps,
      files: [...filesTouched],
    });
  } catch (err) {
    const message = err instanceof Error ? err.message : "Agent loop failed";
    req.log.error({ err }, "Build agent loop failed");
    send({ type: "error", message });
    send({ type: "result", ok: false, summary: `Agent error: ${message}`, steps, files: [...filesTouched] });
  } finally {
    res.end();
  }
});

export default router;
